### ISSUE TITLE
5.1 / 7.1 support?

### ISSUE THREAD

**Issue by gooderist** [JannesP/AudioMirror#1]
Hello, great project!

I was wondering if you could provide some advice on how to extend the number of channels to support 5.1/7.1 surround? I have tried changing the MAX_CHANNELS, avgBytesPerSecond, and KSAUDIO_SPEAKER values in SpeakerWaveProperties.h and MicrophoneWaveProperties.h but this results in a broken driver. Are there any other parts of the code you would recommend looking at?

**Comment by GiacomoCostantini** [comment]
@gooderist did you solve it? @JannesP any hint about why everything works only with 2 channels would be much appreciated

**Comment by gooderist** [comment]
The furthest I got was adding the additional speaker configurations to SpeakerHostPinSupportedDeviceFormats. From there I just used WASAPI loopback to access the samples. Hope that helps.

**Comment by Raj123456788** [comment]
Hello @gooderist, can you please answer this question about debugging: https://github.com/JannesP/AudioMirror/issues/8

**Comment by gooderist** [comment]
Seems like it has already been answered. Just the follow the tutorial, it's
pretty straightforward.

2020年12月23日(水) 2:27 Raj123456788 <notifications@github.com>:

**Comment by JannesP** [comment]
No idea why I never answered back in the day, but I actually tried that and didn't manage to get it working either.
