### ISSUE TITLE
the driver is not listed 'audio input and outputs' but listed 'sound ,video and game controllers'

### ISSUE THREAD

**Issue by shilanzhang** [JannesP/AudioMirror#11]
the driver is not listed 'audio input and outputs' but listed 'sound ,video and game controllers' on the VM.
This should not the code issue. 
Due to this issue, I couldn't set the output to this driver.
do you know what is the reason ?

**Comment by dcsoft4** [comment]
Virtual audio drivers (not just AudioMirror) don't appear in "Audio inputs and outputs", in Hyper-V, if Remote Audio is enabled. AudioMirror does appear in "Audio inputs and outputs" if you disable Remote Audio when connecting to the VM session with RDP or the Hyper-V built-in access.  This makes Hyper-V somewhat useless to test with, as Remote Audio is needed to actually hear sound from the VM on the host PC.  You can verify correct operation in a more inconvenient way by installing an audio recording app that captures and records to a wave file the output of the AudioMirror device.

VMware and Parallels do work normally (I think VirtualBox might also but am not sure).

**Comment by JannesP** [comment]
Very interesting, I didn't know that. I used VirtualBox for testing and that worked as well. Thanks!
