### ISSUE TITLE
Some questions about next steps

### ISSUE THREAD

**Issue by Adonis-Song** [JannesP/AudioMirror#15]
Hi. Thanks for your sharing.

I build this project and find it can pass audio from speaker driver to mic driver ,very cool.  I want to add more functions to it ,just like Loopback on Mac  . But I am new to windows driver, could you please give me some advice? These are some my questions. 

1. How to play sound when audio passed to speaker driver?
2. How to get audio from dirver which connects to hardware?

**Comment by JannesP** [comment]
Hey, sorry to necro this but I'm trying to clean up a bit.
Sadly I'm no expert either and can't really give you any specific advice.
