### ISSUE TITLE
apis to create and destroy AudioMirror Virtual Audio Device?

### ISSUE THREAD

**Issue by TianpingHsu** [JannesP/AudioMirror#16]
Hi, I struggled to compile and install AudioMirror (new to Windows and Windows Driver), it worked ok now.  
I'd like to know if I can create AudioMirror and destroy it by some apis in C++? something like this:  
```C++
// include AudioMirror api header file

// somewhere in my project
{
    if (bCreate) createAudioMirror();
    ......
    if (bDestroy) destroyAudioMirror();
}
```

thank you very much.

Environment:  
Windows 10, Visual Studio 2019, SDK18362, WDK18362, in C++  
(Currently, I just disable enforcement through startup settings to install the unsigned driver)

**Comment by JannesP** [comment]
I tried to add dynamic endpoint creation at some point but for some reason it didn't work. Also: simply accessing any driver from Userspace is not as trivial as using a library, there would be some kind of messaging required.
