### ISSUE TITLE
Tried to compile but I am getting spectre mitigated libs error

### ISSUE THREAD

**Issue by Ajith-Chandran-K** [JannesP/AudioMirror#18]
Hi, I am kinda new but as I was attempting to compile this on my windows VM using VS 2022. It is throwing an error telling me that Spectre Mitigated libraries missing or something along the lines. But i did install it and its still giving me the error. Is there anything I am missing ? :)

**Comment by JannesP** [comment]
You need to install the correct version for your windows SDK. I've never had any problems with it.
