### ISSUE TITLE
Solution builds successfully, installs successfully but devices are not showing up in "Device Manager"

### ISSUE THREAD

**Issue by mujahid-dev** [JannesP/AudioMirror#3]
Hi @JannesP 
Hope you give a look at it.
I'm on Windows 10 (x64) trying to install the driver. Driver gets installed successfully but when i check the Device Manager, no device related to this driver shows up. 
However, when i directly install ".sys" file using a tool, i can see the device(AudioMirror) in "Devicetree" tool but it still doesn't show up in Windows Device Manager.
Is there any configuration i need to do ? 
Any help on this would be much appreciated.
Thanks!

**Comment by JannesP** [comment]
Hey,
it should show up like any other audio device in the device manager. I always installed it with devcon, so no idea how/if other methods work. Here's a screenshot I just took on my "test device" (in my case an old Surface 3). I still had the driver laying around on the desktop and installed it.

![image](https://user-images.githubusercontent.com/5788115/85946963-47b43e00-b948-11ea-9266-4466db063168.png)

**Comment by mujahid-dev** [comment]
Hey @JannesP ,
Thank you very much for your response.
In my case devcon fails with following log...
However, now it does appear in Device Manager as "Unknown Device".

>>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - Root/AudioMirror]
>>>  Section start 2020/06/28 09:33:06.191
      cmd: devcon  install AudioMirror.inf Root/AudioMirror
     ndv: INF path: C:\Users\Dev\AudioMirror\AudioMirror.inf
     ndv: Install flags: 0x00000001
     ndv: {Update Device Driver - ROOT\MEDIA\0002}
     ndv:      Search options: 0x00000080
     ndv:      Searching single INF 'C:\Users\Dev\AudioMirror\AudioMirror.inf'
     dvi:      {Build Driver List} 09:33:06.254
     dvi:           Searching for hardware ID(s):
     dvi:                root/audiomirror
     dvi:      {Build Driver List - exit(0x00000000)} 09:33:06.345
!    ndv:      **No matching drivers found in single INF**
     dvi:      {DIF_SELECTBESTCOMPATDRV} 09:33:06.369
     dvi:           Using exported function 'MediaClassInstaller' in module 'C:\Windows\system32\mmci.dll'.
     dvi:           Class installer == mmci.dll,MediaClassInstaller
     dvi:           Class installer: Enter 09:33:06.380
     dvi:           Class installer: Exit
     dvi:           Default installer: Enter 09:33:06.399
     dvi:                {Select Best Driver}
!    dvi:                     Selecting driver failed(0xe0000228)
     dvi:                {Select Best Driver - exit(0xe0000228)}
!    dvi:           Default installer: failed
!    dvi:           **Error 0xe0000228: There are no compatible drivers for this device.**
     dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0xe0000228)} 09:33:06.444
!    ndv:      Unable to select best compatible driver. Error = 0xe0000228
     ndv:      No drivers found for device.
     ndv: {Update Device Driver - exit(00000103)}
!    ndv: No better matching drivers found for device 'ROOT\MEDIA\0002'.
!    ndv: No devices were updated.
     dvi: {DIF_DESTROYPRIVATEDATA} 09:33:06.493
     dvi:      Class installer: Enter 09:33:06.506
     dvi:      Class installer: Exit
     dvi:      Default installer: Enter 09:33:06.526
     dvi:      Default installer: Exit
     dvi: {DIF_DESTROYPRIVATEDATA - exit(0xe000020e)} 09:33:06.538
<<<  Section end 2020/06/28 09:33:06.538
<<<  [Exit status: FAILURE(0x00000103)]

**Comment by JannesP** [comment]
I think you accidentally used a normal slash in the device path name in the devcon command:
`devcon install AudioMirror.inf Root/AudioMirror`
should be
`devcon install AudioMirror.inf Root\AudioMirror`

**Comment by mujahid-dev** [comment]
> I think you accidentally used a normal slash in the device path name in the devcon command:
> `devcon install AudioMirror.inf Root/AudioMirror`
> should be
> `devcon install AudioMirror.inf Root\AudioMirror`

Lol ! 
Thats a muscle memory side-effect when u come from linux world :)
Anyways, Thank u very much for ur time @JannesP  :)
Installed !

**Comment by JannesP** [comment]
No problem, glad it works now 😄 
Good luck with further development.
