### ISSUE TITLE
Any Documentation or Steps to Start

### ISSUE THREAD

**Issue by Raj123456788** [JannesP/AudioMirror#4]
Hi @JannesP : Thank you for the repo. Can you please add any documentation or helpful links for the repo?

**Comment by JannesP** [comment]
https://github.com/JannesP/AudioMirror/commit/439c5241747e7075736309dc6ff66a90cc9e0557

**Comment by Xoib** [comment]
Hi @JannesP ; Would it be possible to include the binaries as Github release for those who don't have the whole development requirements on their computer? Thanks!

**Comment by JannesP** [comment]
No, I'm not gonna provide any binaries since the driver isn't 100% stable and has some quirks here and there.
If you can't build the driver yourself then you won't gain anything from the binaries, sorry.

**Comment by Xoib** [comment]
![image](https://user-images.githubusercontent.com/511705/99812993-6a3d3280-2b47-11eb-8752-8bfc9639b11a.png)

All those aren't found.
I have installed the WDK on top of VS 2019.
Still looking for a solution. Will edit if I find.

**Comment by Xoib** [comment]
Well I have the correct SDK and WDK but I keep getting: 
![image](https://user-images.githubusercontent.com/511705/99814189-ee43ea00-2b48-11eb-9966-841953d7b843.png)

WDK has been installed from .exe from the documentation.

SDK : 
![image](https://user-images.githubusercontent.com/511705/99814288-15022080-2b49-11eb-8848-a3310ba799f8.png)

**Comment by Xoib** [comment]
I am blocked for the installation : 

![image](https://user-images.githubusercontent.com/511705/99825461-5b5e7c00-2b57-11eb-817d-89b22ed79665.png)

**Comment by Simon311** [comment]
@JannesP Should've written this with big letters in your README. Two downloads of kits and SDKs later your shit still wouldn't build, complaining about 24 unresolved externals, and only now do I hear that if I can't code a driver like this from the ground up - this one won't be useful to me either. Thanks for dumping a non-functional project onto the internet.

**Comment by JannesP** [comment]
> Two downloads of kits and SDKs later your shit still wouldn't build, complaining about 24 unresolved externals

Well, it worked the last time I used it. But apparently time breaks things. I do know of people that got it to compile ... so there appears to be an error on your part. Good luck on getting any help with those manners though :)
