### ISSUE TITLE
Getting this error only during building for Release x64

### ISSUE THREAD

**Issue by Raj123456788** [JannesP/AudioMirror#7]
Hi James,

C:\Users\Downloads\AudioMirror-master (1)\AudioMirror-master\AudioMirror\AdapterCommon.cpp(112,96): error C2220: **the following warning is treated as an error**

For this line of code 
if (!NT_SUCCESS(ntStatus)) DPF(D_TERSE, ("PcGetPhysicalDeviceObject failed, 0x%x", ntStatus));

I have tried to compile with (/WX-) along with  /W3

**Comment by Raj123456788** [comment]
![image](https://user-images.githubusercontent.com/16295521/101840283-a802fa80-3af8-11eb-8dc1-c332fe04245d.png)

**Comment by findmeabug** [comment]
I'm having the same issue but adding those two libraries didn't solve it. Was that the only change you did to build it?

[edit] Nevermind, I thought I set the warning flag but didn't lol
