### ISSUE TITLE
How to debug this driver during run time?

### ISSUE THREAD

**Issue by Raj123456788** [JannesP/AudioMirror#8]
Hello again,
can you please guide me through steps to debug this driver.

It builds fine and I can install it it. But if I need to debug how would one debug it?

**Comment by JannesP** [comment]
Debugging works like any other kernel mode driver, please refer to the docs: [MSDN](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers--kernel-mode-)
