### ISSUE TITLE
While building release version getting the following  linker issues

### ISSUE THREAD

**Issue by Debangshu132** [JannesP/AudioMirror#9]
Build started...
1>------ Build started: Project: AudioMirror, Configuration: Release x64 ------
1>Building 'AudioMirror' with toolset 'WindowsKernelModeDriver10.0' and the 'Universal' target platform.
1>Stamping x64\Release\AudioMirror.inf
1>Stamping [Version] section with DriverVer=05/06/2021,5.33.21.519
1>C:\audiomirror\AudioMirror\AudioMirror\AudioMirror.inf(5-5): warning 1324: [Version] section should specify PnpLockdown=1.
1>AdapterCommon.obj : error LNK2019: unresolved external symbol __imp_PcGetPhysicalDeviceObject referenced in function "public: virtual long __cdecl AdapterCommon::Init(struct _IRP *,struct _DEVICE_OBJECT *)" (?Init@AdapterCommon@@UEAAJPEAU_IRP@@PEAU_DEVICE_OBJECT@@@Z)
1>AdapterCommon.obj : error LNK2019: unresolved external symbol "public: __cdecl CUnknown::CUnknown(struct IUnknown *)" (??0CUnknown@@QEAA@PEAUIUnknown@@@Z) referenced in function "public: static long __cdecl AdapterCommon::Create(struct IUnknown * *,struct _GUID const &,struct IUnknown *,enum _POOL_TYPE,struct _DEVICE_OBJECT *,struct _IRP *)" (?Create@AdapterCommon@@SAJPEAPEAUIUnknown@@AEBU_GUID@@PEAU2@W4_POOL_TYPE@@PEAU_DEVICE_OBJECT@@PEAU_IRP@@@Z)
1>MiniportTopology.obj : error LNK2001: unresolved external symbol "public: __cdecl CUnknown::CUnknown(struct IUnknown *)" (??0CUnknown@@QEAA@PEAUIUnknown@@@Z)
1>MiniportWaveRT.obj : error LNK2001: unresolved external symbol "public: __cdecl CUnknown::CUnknown(struct IUnknown *)" (??0CUnknown@@QEAA@PEAUIUnknown@@@Z)
1>AdapterCommon.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl CUnknown::~CUnknown(void)" (??1CUnknown@@UEAA@XZ) referenced in function "public: virtual __cdecl AdapterCommon::~AdapterCommon(void)" (??1AdapterCommon@@UEAA@XZ)
1>MiniportTopology.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl CUnknown::~CUnknown(void)" (??1CUnknown@@UEAA@XZ)
1>MiniportWaveRT.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl CUnknown::~CUnknown(void)" (??1CUnknown@@UEAA@XZ)
1>MiniportWaveRTStream.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl CUnknown::~CUnknown(void)" (??1CUnknown@@UEAA@XZ)
1>AdapterCommon.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingAddRef(void)" (?NonDelegatingAddRef@CUnknown@@UEAAKXZ)
1>MiniportTopology.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingAddRef(void)" (?NonDelegatingAddRef@CUnknown@@UEAAKXZ)
1>MiniportWaveRT.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingAddRef(void)" (?NonDelegatingAddRef@CUnknown@@UEAAKXZ)
1>MiniportWaveRTStream.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingAddRef(void)" (?NonDelegatingAddRef@CUnknown@@UEAAKXZ)
1>AdapterCommon.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingRelease(void)" (?NonDelegatingRelease@CUnknown@@UEAAKXZ)
1>MiniportTopology.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingRelease(void)" (?NonDelegatingRelease@CUnknown@@UEAAKXZ)
1>MiniportWaveRT.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingRelease(void)" (?NonDelegatingRelease@CUnknown@@UEAAKXZ)
1>MiniportWaveRTStream.obj : error LNK2001: unresolved external symbol "public: virtual unsigned long __cdecl CUnknown::NonDelegatingRelease(void)" (?NonDelegatingRelease@CUnknown@@UEAAKXZ)
1>Driver.obj : error LNK2019: unresolved external symbol __imp_PcInitializeAdapterDriver referenced in function DriverEntry
1>Driver.obj : error LNK2019: unresolved external symbol __imp_PcDispatchIrp referenced in function "long __cdecl PnpHandler(struct _DEVICE_OBJECT *,struct _IRP *)" (?PnpHandler@@YAJPEAU_DEVICE_OBJECT@@PEAU_IRP@@@Z)
1>Driver.obj : error LNK2019: unresolved external symbol __imp_PcAddAdapterDevice referenced in function "long __cdecl AddDevice(struct _DRIVER_OBJECT *,struct _DEVICE_OBJECT *)" (?AddDevice@@YAJPEAU_DRIVER_OBJECT@@PEAU_DEVICE_OBJECT@@@Z)
1>SubdeviceHelper.obj : error LNK2019: unresolved external symbol __imp_PcRegisterSubdevice referenced in function "private: long __cdecl SubdeviceHelper::InstallSubdevice(struct _IRP *,unsigned short *,unsigned short *,struct _GUID const &,struct _GUID const &,long (__cdecl*)(struct IUnknown * *,struct _GUID const &,struct IUnknown *,enum _POOL_TYPE,struct IUnknown *,void *,struct _ENDPOINT_MINIPAIR *),unsigned long,struct _SYSVAD_DEVPROPERTY const *,void *,struct _ENDPOINT_MINIPAIR *,struct IResourceList *,struct _GUID const &,struct IUnknown * *,struct IUnknown * *,struct IUnknown * *)" (?InstallSubdevice@SubdeviceHelper@@AEAAJPEAU_IRP@@PEAG1AEBU_GUID@@2P6AJPEAPEAUIUnknown@@2PEAU4@W4_POOL_TYPE@@4PEAXPEAU_ENDPOINT_MINIPAIR@@@ZKPEBU_SYSVAD_DEVPROPERTY@@67PEAUIResourceList@@2333@Z)
1>SubdeviceHelper.obj : error LNK2019: unresolved external symbol __imp_PcRegisterPhysicalConnection referenced in function "private: long __cdecl SubdeviceHelper::ConnectTopologies(struct IUnknown *,struct IUnknown *,struct _PHYSICALCONNECTIONTABLE *,unsigned long)" (?ConnectTopologies@SubdeviceHelper@@AEAAJPEAUIUnknown@@0PEAU_PHYSICALCONNECTIONTABLE@@K@Z)
1>SubdeviceHelper.obj : error LNK2019: unresolved external symbol __imp_PcNewPort referenced in function "private: long __cdecl SubdeviceHelper::InstallSubdevice(struct _IRP *,unsigned short *,unsigned short *,struct _GUID const &,struct _GUID const &,long (__cdecl*)(struct IUnknown * *,struct _GUID const &,struct IUnknown *,enum _POOL_TYPE,struct IUnknown *,void *,struct _ENDPOINT_MINIPAIR *),unsigned long,struct _SYSVAD_DEVPROPERTY const *,void *,struct _ENDPOINT_MINIPAIR *,struct IResourceList *,struct _GUID const &,struct IUnknown * *,struct IUnknown * *,struct IUnknown * *)" (?InstallSubdevice@SubdeviceHelper@@AEAAJPEAU_IRP@@PEAG1AEBU_GUID@@2P6AJPEAPEAUIUnknown@@2PEAU4@W4_POOL_TYPE@@4PEAXPEAU_ENDPOINT_MINIPAIR@@@ZKPEBU_SYSVAD_DEVPROPERTY@@67PEAUIResourceList@@2333@Z)
1>SubdeviceHelper.obj : error LNK2019: unresolved external symbol __imp_PcNewMiniport referenced in function "private: long __cdecl SubdeviceHelper::InstallSubdevice(struct _IRP *,unsigned short *,unsigned short *,struct _GUID const &,struct _GUID const &,long (__cdecl*)(struct IUnknown * *,struct _GUID const &,struct IUnknown *,enum _POOL_TYPE,struct IUnknown *,void *,struct _ENDPOINT_MINIPAIR *),unsigned long,struct _SYSVAD_DEVPROPERTY const *,void *,struct _ENDPOINT_MINIPAIR *,struct IResourceList *,struct _GUID const &,struct IUnknown * *,struct IUnknown * *,struct IUnknown * *)" (?InstallSubdevice@SubdeviceHelper@@AEAAJPEAU_IRP@@PEAG1AEBU_GUID@@2P6AJPEAPEAUIUnknown@@2PEAU4@W4_POOL_TYPE@@4PEAXPEAU_ENDPOINT_MINIPAIR@@@ZKPEBU_SYSVAD_DEVPROPERTY@@67PEAUIResourceList@@2333@Z)
1>C:\audiomirror\AudioMirror\x64\Release\AudioMirror.sys : fatal error LNK1120: 12 unresolved externals
1>Done building project "AudioMirror.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jerrychen-dev** [comment]
Hi Sir,
I have the same issue, too.
Can you kindly tell me how to solve this issue?

**Comment by TianpingHsu** [comment]
@jerrychen-dev it means those symbols are not defined (compiler can find the declaration in some header files (portcls.h, stdunk.h), but linker can not find the implementation of them).  
you need to configure the linker:  
Project -> Properties  -> Linker -> Input -> Additional dependencies  
explicitly specify the libs: 
Portcls.lib
Stdunk.lib

you may check https://stackoverflow.com/questions/4066405/when-to-use-the-visual-studio-additional-dependencies
